### PR TITLE
TIQR-248: Fix issue with kerning

### PR DESCRIPTION
**Pull request by welsinga**

### CODE REVIEW

**Review by dzolnai — APPROVED** [review]
Interesting, 0 is the default value, so this would not change anything?

**Comment by welsinga** [comment]
> Interesting, 0 is the default value, so this would not change anything?

before
after

**Comment by welsinga** [comment]
It is in the font file

**Comment by dzolnai** [comment]
Hm, probably the font has some built-in kerning which is then overridden via the style. Looks good!

**Pull request merged**
